CORS_ALLOWED_ORIGINS: "http://www.google.com"

server:
  port: 8080

auth:
  cors:
    path-mappings: /**
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: [ "POST", "PUT", "DELETE" ]
    allowed-headers: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG