server:
  port: 8302
  servlet:
    context-path: /monitoring

spring:
  application:
    # displayed name in the admin dashboard
    name: monitoring-1

  security:
    user:
      name: student
      password: secret

  boot:
    admin:
      client:
        url: http://localhost:8300/monitoring-admin
        username: monitoring
        password: secret
        # configuration for client (data sent to the server to connect to client)
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        # configuration for server
        routes:
          endpoints: ${management.endpoints.web.exposure.include}

management:
  endpoint:
    health:
      # used by spring boot admin
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health      # http://localhost:8302/monitoring/actuator/health
          - info        # http://localhost:8302/monitoring/actuator/info
          - metrics     # http://localhost:8302/monitoring/actuator/metrics
          - prometheus  # http://localhost:8302/monitoring/actuator/prometheus
          - env         # http://localhost:8302/monitoring/actuator/env
          - beans       # http://localhost:8302/monitoring/actuator/beans
          - mappings    # http://localhost:8302/monitoring/actuator/mappings
